### PR TITLE
add new arena model

### PR DESCRIPTION
**Pull request by tongtybj**
@cretaceous-creature 
Please chk
1. I add new arena model. which contains the texture material. 
  just have a try with: $ gazebo mbzirc_arena.world
  I also confirm that new arena is ok for husky:
 $ROBOT_INITIAL_POSE="-x 65 -y -25 -z 1" roslaunch jsk_mbzirc_ugv_sim husky_mbzirc.launch

2. I suppose that the mbzirc_arena.world for each task should be specialized, such as mbzirc_arena_task1.world, mbzirc_arena_task2.world, mbzirc_arena_task3.world, mbzirc_arena_task4.world. Because the environment of each task is slightly different.

3. I also suppose that the it is better to move the directory "gazebo_model"  into package "jsk_mbzirc_common" or change the "gazebo_model" to ros package.

### CODE REVIEW

**Comment by cretaceous-creature** [comment]
And for the husky,  the deb package is buggy and without gripper,
we need to build from the recent source code if we want to perform the
simulation.

Are we going to use husky?

2016-01-05 16:53 GMT+09:00 趙 漠居 <notifications@github.com>:

**Comment by tongtybj** [comment]
uh, it seems like building from source is a boring task, but still not
difficult.
We can use husky+ur5 just for simuliation, like the
percepition/munipulation process.

But the best choice I believe is the car you showed in taobao + the staro
arm.
The only thing I am concern about the staro arm is that there is no
professional person in our team to deal with urata-board series product.


2016-01-05 17:58 GMT+09:00 Chen <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
The car from taobao is only 10+kg, it is unable to carry more than 20kg...
And as it become heavier, it become slower....
we need a 4m/s UGV....

2016-01-05 18:07 GMT+09:00 趙 漠居 <notifications@github.com>:

**Comment by tongtybj** [comment]
One solution you said is to change the motor_driver to urata-board?
Is it still feasible?
What is your best  option?

2016-01-05 18:12 GMT+09:00 Chen <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
it depends how much we can get.....
how much is husky?
I know UR5 is about 3 million yen.....

Change the motor is not very hard, but then I need to
change the software then.....
I hope Japan have such kind of moving base...

2016-01-05 18:14 GMT+09:00 趙 漠居 <notifications@github.com>:

**Pull request merged**
