### PR TITLE
Add task2 test

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by cretaceous-creature** [comment]
Merge?

**Comment by cretaceous-creature** [comment]
merged

**Comment by k-okada** [comment]
thanks, I think we should use 'master' as default branch name, because our
code is not strongly depend on idnigo
so
1)  remove current master brranch
2) rename indigo-devel to master branch
3) set master as default branch

--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
Thank you very much okada sensei, I will login and change that...
I have just tested the task2, it seems the initial husky arm pose is 
conflicting with the husky base, so the arm could not move... I am not sure
if it is my problem...

**Comment by k-okada** [comment]
Run this mode manually
https://github.com/tongtybj/mbzirc/blob/master/jsk_mbzirc_tasks/launch/jsk_mbzirc_task_2.launch#L39

And if you look your log carefully, you can see the error message that says it can not connected controller, we'd better to catch that error and resend the command
--
◉ Kei Okada

2016/01/22 13:03、Chen <notifications@github.com> のメッセージ:

**Comment by cretaceous-creature** [comment]
I got it, thank you.

2016-01-22 13:19 GMT+09:00 Kei Okada <notifications@github.com>:

**Pull request merged**
