### PR TITLE
move uav_teleop_keyboard to  jsk_mbzirc_tasks, no launch file in jsK_mbzirc_common use them

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by tongtybj** [comment]
merge?

**Comment by k-okada** [comment]
if you and @cretaceous-creature is ok with this

**Comment by cretaceous-creature** [comment]
I am fine with okada sensei's idea of using teleop_twist_keyboard , but in fact I prefer to use the 
keyboard layout of uav_teleop_keyboard for both uav and ugv...   
Better to leave this node in task for custom use than remove it....

**Comment by k-okada** [comment]
if so, you can send PR to switch keybindings in teleop_twist_keyboad, you 
can also check https://github.com/ros-teleop/teleop_tools

--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
OK, okada sensei,
Thank you very much.

2016-01-24 19:17 GMT+08:00 Kei Okada <notifications@github.com>:

> if so, you can send PR to switch keybindings in teleop_twist_keyboad, you
> can also check https://github.com/ros-teleop/teleop_tools
>
> --
> ◉ Kei Okada
>
>

**Pull request merged**
