### PR TITLE
Fix gazebo plugin

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by tongtybj** [comment]
I have confimed that all launch files work in my PC

@cretaceous-creature 
Could you please try or should I merge this immediately?

**Comment by cretaceous-creature** [comment]
No problem for me

2016年1月14日木曜日、趙 漠居<notifications@github.com>さんは書きました:

**Comment by k-okada** [comment]
The map direction was back to the old direction by this merge, are you sure
about this ?

2016年1月14日木曜日、Chen<notifications@github.com>さんは書きました:

> Merged #23 <https://github.com/tongtybj/mbzirc/pull/23>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tongtybj/mbzirc/pull/23#event-514428512>.
>


-- 
--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
I have downloaded okada sensei's branch and fix the map problem,
now I think it is OK for me now.
I will add the wrench and trying to fix the gripper today....

2016-01-14 10:30 GMT+09:00 Kei Okada <notifications@github.com>:

**Pull request merged**
